version: '3.7'

services:
  # boleto-api:
  #   container_name: boleto-api
  #   restart: on-failure
  #   build: .
  #   volumes:
  #     - .:/app
  #   ports:
  #     - ${PORT}:${PORT}
  #   env_file:
  #     - .env
  #   command: yarn start:dev
  #   depends_on:
  #     - postgres
  #     - rabbitmq

  postgres:
    image: postgres:alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    container_name: postgres
    volumes:
      - pg-boleto-api-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    ports:
      - 5672:5672  
      - 15672:15672  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  

volumes:
  pg-boleto-api-data:
  rabbitmq_data:
